on:
  workflow_dispatch: {}
  schedule:
    # Makes commit(s) at 9am daily
    # Change to whatever cron expression you like
    - cron: "1/10 10 * * *"

jobs:
  lit-job:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    name: A job to get you lit
    steps:
      - uses: actions/checkout@v3
      - name: make commits
        # Uses GitHub action defined in https://github.com/FredaXin/gitlit
        uses: NormTurtle/gitlit@main
        with:
          # Defines the range of number of commits
          # Change to your desierd lower and upper bound
          lower-bound: 10
          upper-bound: 10000
          # Change to your GitHub username
          user-name: NormTurtle
          # Change to your email used for GitHub account
          user-email: Omix1.ok@gmail.com
